"""Added final price field to order.

Revision ID: 17df8e650a81
Revises: 7c004bf5c26c
Create Date: 2021-12-25 17:31:34.269091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17df8e650a81'
down_revision = '7c004bf5c26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('final_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'final_price')
    # ### end Alembic commands ###
